### ISSUE TITLE
Falsche Übersetzung in animierter Karte 

### ISSUE THREAD

**Issue by herrhundt** [herrhundt/remember#2]
In Zeile 204 ist die Simulation verlinkt [sims/singlecard/?card=spaced_rep"](url), jedoch taucht hier ein Schreibfehler (ss) auf. Wer findet heraus, wie man das beheben kann? Bitte dazu einen passenden PR erstellen.

**Comment by its-nico** [comment]
Ab L2255 ist der CSS Code für alle Flashcards. 
Ich eröffne gleich ein PR dafür und schaue, ob ich alle Rechtschreibfehler finde.

@ everyone: Bitte auf die Übersetzungshinweise achten:
The CSS for the flashcards is really touchy, so DO NOT MODIFY THE CSS.
That means, try as much as possible to make your text shorter or the same length as the original text.
Good luck!
