### ISSUE TITLE
Missing Examples

### ISSUE THREAD

**Issue by randomcmd** [herrhundt/remember#20]
Line 2623 in de.html

**Comment by its-nico** [comment]
Verstehe nicht ganz, was du meinst, aber schau mal im PR L2003-2670 nach, dort habe ich diesen Zeilenbereich überarbeitet, vielleicht ist das Problem dort gelöst.

**Comment by herrhundt** [comment]
Ich bin mir auch nicht sicher, was du genau meinst. Kannst du es erläutern? Falls sich das Anliegen geklärt hat, bitte das Issue als "closed" markieren.
