### ISSUE TITLE
fehlende Credits

### ISSUE THREAD

**Issue by herrhundt** [herrhundt/remember#30]
Wie im PR 29 vorgeschlagen (https://github.com/herrhundt/remember/pull/29), sollten diese nicht im header auftauchen, da durch die Länge sonst das Design zerschossen wird. 

Vielleicht hat ja jemand von euch eine Idee, wo wir unsere Credits unterbringen.

**Comment by its-nico** [comment]
Also dieser Simon Stelling hat in den Credits seinen Namen auch noch mal dazugeschrieben, und zwar neben "Written, drawn, and programmed by Nicky Case", was ich ein bisschen anmaßend finde...
Vielleicht können wir dort einfach drunterschreiben:
Übersetzt von: Simon Stelling, [unsere Namen]

![Screenshot (353)](https://user-images.githubusercontent.com/65342313/82146747-b59b1f00-984c-11ea-89ba-e85970ccf7ec.png)

**Comment by herrhundt** [comment]
Grundsätzlich gut, nur wird das Design auch dort zerschossen. Man muss hier wohl die entsprechende Box im HTML bzw. CSS-Code verändern. Hier kümmere ich mich drum. 
![Unbenannt](https://user-images.githubusercontent.com/59929867/82228126-01bb9180-9929-11ea-8d4a-64a8ac6da6ae.png)
