### ISSUE TITLE
Begriffsklärung: spaced repitition

### ISSUE THREAD

**Issue by herrhundt** [herrhundt/remember#33]
Hi zusammen, 
in einem Issue des orginalen Repos wurde darüber diskutiert, ob "Intervall-Lernen" nicht eine bessere Übersetzung von spaced repitition ist, siehe (https://github.com/ncase/remember/issues/2). 
Wie seht ihr das?

**Comment by Picman2000** [comment]
Finde das passt gut. Auf jeden Fall besser als was da sonst noch im Threat stehtwie z.B "Wiederholungen in regelmäßigen Abständen"

**Comment by herrhundt** [comment]
Siehe PR https://github.com/herrhundt/remember/pull/36
